In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('/content/car_prices.csv')
data

,car_id,price,fuel type,gear type,Make,Model,Year of manufacture,Colour,Condition,Mileage,Engine Size,Selling Condition,Bought Condition,car,Trim,Drivetrain,Seats,Number of Cylinders,Horse Power,Registered city
0,icwAaDOmX573WiRRnLFPT237,2812500,Petrol,Automatic,Toyota,Corolla,2004,Silver,Nigerian Used,251732.0,1800.0,Registered,Registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ByZ3NlPy2x0arAIyrKazClUS,5000000,Petrol,Automatic,Acura,MDX,2007,Green,Foreign Used,224589.0,3700.0,Imported,Imported,SUV,NaN,NaN,NaN,NaN,NaN,NaN
2,2zG6Mh3kwyoTvWoeKHkV1oFH,7592000,Petrol,Automatic,Acura,TL,2012,White,Foreign Used,111334.0,3500.0,Imported,Imported,Sedan,SH-AWD Automatic Tech Package,All Wheel,5.0,6.0,309.0,NaN
3,7APLHOPlI93qsYK0ST4D4wB2,9880000,Petrol,Automatic,Land Rover,Range Rover,2012,Gray,Nigerian Used,72682.0,4000.0,Registered,Imported,SUV,NaN,NaN,NaN,NaN,NaN,NaN
4,zIrIDPJLd46eRQf9JFacc0e,4160000,Petrol,Automatic,Ford,Edge,2013,Gray,Nigerian Used,92118.0,3500.0,Registered,Registered,SUV,NaN,NaN,NaN,NaN,NaN,Lagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3717,C4Ly76wwazrtbYRAWkTnv2Q5,1924000,Petrol,Automatic,Toyota,RAV4,2003,Red,Nigerian Used,282769.0,2000.0,Registered,Imported,SUV,Automatic,All Wheel,5.0,4.0,NaN,Plateau
3718,jPA7XlJJxdwpZStlurumw59q,1890000,Petrol,Automatic,Mercedes-Benz,M Class,2002,Silver,Nigerian Used,182544.0,3200.0,Registered,Registered,SUV,ML 320,All Wheel,5.0,6.0,215.0,NaN
3719,g5szhuHeXu2djH1Z2be22G7E,1155000,Petrol,Automatic,Toyota,Camry,2000,Black,Nigerian Used,234354.0,2200.0,Registered,Registered,Sedan,LE 4dr Sedan (2.2L 4cyl 4A),Front,5.0,4.0,136.0,RIVERS
3720,mdZMNQK7Zez0cSS67Q9Quhzr,1260000,Petrol,Automatic,Toyota,RAV4,2001,Black,Nigerian Used,345926.0,2000.0,Registered,Registered,SUV,NaN,NaN,NaN,NaN,NaN,NaN
3721,fSUvulLwnXYlc1muFsrjrsAR,1872000,Petrol,Automatic,Honda,Civic,2007,Black,Nigerian Used,90330.0,1800.0,Registered,Registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3722 entries, 0 to 3721
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   car_id               3722 non-null   object
 1   price                3722 non-null   int64
 2   fuel type            3721 non-null   object
 3   gear type            3720 non-null   object
 4   Make                 3722 non-null   object
 5   Model                3722 non-null   object
 6   Year of manufacture  3722 non-null   int64
 7   Colour               3717 non-null   object
 8   Condition            3722 non-null   object
 9   Mileage              3663 non-null   float64
 10  Engine Size          3661 non-null   float64
 11  Selling Condition    3722 non-null   object
 12  Bought Condition     3722 non-null   object
 13  car                  1767 non-null   object
 14  Trim                 879 non-null    object
 15  Drivetrain           838 non-null    object
 16  Seats                788 non-null    float64
 17  Number of Cylinders  826 non-null    float64
 18  Horse Power          755 non-null    float64
 19  Registered city      1901 non-null   object
dtypes: float64(5), int64(2), object(13)
memory usage: 581.7+ KB

In [5]:
data.describe()

,price,Year of manufacture,Mileage,Engine Size,Seats,Number of Cylinders,Horse Power
count,3.722000e+03,3722.000000,3.663000e+03,3.661000e+03,788.000000,826.000000,755.000000
mean,4.514644e+06,2008.145889,1.949841e+05,1.108062e+04,5.285533,5.157385,208.831788
std,4.297012e+06,4.205670,1.395755e+05,1.091127e+05,0.800853,1.202795,70.940925
min,5.500000e+05,1979.000000,1.000000e+00,1.800000e+02,2.000000,4.000000,83.000000
25%,2.310000e+06,2005.000000,1.173945e+05,2.000000e+03,5.000000,4.000000,158.000000
50%,3.360000e+06,2008.000000,1.762900e+05,2.500000e+03,5.000000,6.000000,203.000000
75%,5.036250e+06,2011.000000,2.453815e+05,3.500000e+03,5.000000,6.000000,268.000000
max,6.240000e+07,2022.000000,2.456318e+06,3.500000e+06,8.000000,8.000000,585.000000

In [6]:
data.isnull().sum()

car_id                    0
price                     0
fuel type                 1
gear type                 2
Make                      0
Model                     0
Year of manufacture       0
Colour                    5
Condition                 0
Mileage                  59
Engine Size              61
Selling Condition         0
Bought Condition          0
car                    1955
Trim                   2843
Drivetrain             2884
Seats                  2934
Number of Cylinders    2896
Horse Power            2967
Registered city        1821
dtype: int64

In [36]:
data['Registered city'].value_counts()

Registered city
LAGOS          804
Lagos          399
ABUJA          185
Abuja          143
RIVERS          39
              ...
ABIA             1
Nasarawa         1
FKJ-880HM        1
Osun             1
RIVER STATE      1
Name: count, Length: 71, dtype: int64

In [33]:
data.isnull().sum()

car_id                    0
price                     0
fuel type                 1
gear type                 2
Make                      0
Model                     0
Year of manufacture       0
Colour                    5
Condition                 0
Mileage                  59
Engine Size              61
Selling Condition         0
Bought Condition          0
car                       0
Trim                      0
Drivetrain                0
Seats                     0
Number of Cylinders       0
Horse Power               0
Registered city        1821
dtype: int64

In [8]:
data['Drivetrain'].fillna(data['Drivetrain'].mode()[0], inplace = True)

In [11]:
data['car'].fillna(data['car'].mode()[0], inplace = True)

In [17]:
data['Seats'].fillna(data['Seats'].median(), inplace = True)

In [20]:
data['Number of Cylinders'].fillna(data['Number of Cylinders'].median(), inplace = True)

In [23]:
data['Horse Power'].fillna(data['Horse Power'].median(), inplace = True)

In [32]:
data['Trim'].fillna(data['Trim'].()[0], inplace = True)

In [40]:
data.dropna(axis=0, how='any')

,car_id,price,fuel type,gear type,Make,Model,Year of manufacture,Colour,Condition,Mileage,Engine Size,Selling Condition,Bought Condition,car,Trim,Drivetrain,Seats,Number of Cylinders,Horse Power,Registered city
0,icwAaDOmX573WiRRnLFPT237,2812500,Petrol,Automatic,Toyota,Corolla,2004,Silver,Nigerian Used,251732.0,1800.0,Registered,Registered,SUV,LE 4dr Sedan (2.4L 4cyl 5A),All Wheel,5.0,6.0,203.0,LAGOS
1,ByZ3NlPy2x0arAIyrKazClUS,5000000,Petrol,Automatic,Acura,MDX,2007,Green,Foreign Used,224589.0,3700.0,Imported,Imported,SUV,LE 4dr Sedan (2.4L 4cyl 5A),All Wheel,5.0,6.0,203.0,LAGOS
2,2zG6Mh3kwyoTvWoeKHkV1oFH,7592000,Petrol,Automatic,Acura,TL,2012,White,Foreign Used,111334.0,3500.0,Imported,Imported,Sedan,SH-AWD Automatic Tech Package,All Wheel,5.0,6.0,309.0,LAGOS
3,7APLHOPlI93qsYK0ST4D4wB2,9880000,Petrol,Automatic,Land Rover,Range Rover,2012,Gray,Nigerian Used,72682.0,4000.0,Registered,Imported,SUV,LE 4dr Sedan (2.4L 4cyl 5A),All Wheel,5.0,6.0,203.0,LAGOS
4,zIrIDPJLd46eRQf9JFacc0e,4160000,Petrol,Automatic,Ford,Edge,2013,Gray,Nigerian Used,92118.0,3500.0,Registered,Registered,SUV,LE 4dr Sedan (2.4L 4cyl 5A),All Wheel,5.0,6.0,203.0,Lagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3717,C4Ly76wwazrtbYRAWkTnv2Q5,1924000,Petrol,Automatic,Toyota,RAV4,2003,Red,Nigerian Used,282769.0,2000.0,Registered,Imported,SUV,Automatic,All Wheel,5.0,4.0,203.0,Plateau
3718,jPA7XlJJxdwpZStlurumw59q,1890000,Petrol,Automatic,Mercedes-Benz,M Class,2002,Silver,Nigerian Used,182544.0,3200.0,Registered,Registered,SUV,ML 320,All Wheel,5.0,6.0,215.0,LAGOS
3719,g5szhuHeXu2djH1Z2be22G7E,1155000,Petrol,Automatic,Toyota,Camry,2000,Black,Nigerian Used,234354.0,2200.0,Registered,Registered,Sedan,LE 4dr Sedan (2.2L 4cyl 4A),Front,5.0,4.0,136.0,RIVERS
3720,mdZMNQK7Zez0cSS67Q9Quhzr,1260000,Petrol,Automatic,Toyota,RAV4,2001,Black,Nigerian Used,345926.0,2000.0,Registered,Registered,SUV,LE 4dr Sedan (2.4L 4cyl 5A),All Wheel,5.0,6.0,203.0,LAGOS
3721,fSUvulLwnXYlc1muFsrjrsAR,1872000,Petrol,Automatic,Honda,Civic,2007,Black,Nigerian Used,90330.0,1800.0,Registered,Registered,SUV,LE 4dr Sedan (2.4L 4cyl 5A),All Wheel,5.0,6.0,203.0,LAGOS