In [ ]:
pip install termcolor

Requirement already satisfied: termcolor in /usr/local/lib/python3.10/dist-packages (2.4.0)

In [ ]:
import random
from termcolor import colored
options = ['true', 'false']
correct_answer = {
    1:'true',
    2:'true',
    3:'true',
    4:'true',
    5:'true',
    6:'true',
    7:'true',
    8:'true',
    9:'true',
    10:'true'
    }
the_questions = {
    1:'SQL stands for "Structured Querry Language.',
    2:'The SELECT statement is used in SQL to retrieve data from a table.',
    3:'In SQL, the WHERE clause is used to filter rows based on a specified condition.',
    4:'SQL JOIN clause is used to combine rows from two or more tables, based on a related column between them.',
    5:'In SQL, the GROUP BY clause is used to group rows that have the same values into summary rows.',
    6:"SQL's AVG() function is used to find the average value of a numeric row.",
    7:'The INSERT INTO statement is used in SQL to add new records (rows) to a table',
    8:"SQL's COUNT() function returns the number of rows that satisfy a specified condition.",
    9:"SQL's ORDER BY clause is used to sort the result set in ascending or descending order based on one or more columns.",
    10:"SQL's UPDATE statement is used to modify existing records in a column."
    }

class Player:
    def __init__(self, name, gender, age, state_of_origin):
        self.name = name
        self.gender = gender
        self.age = age
        self.state_of_origin = state_of_origin
        self.score = 0
        self.question_counter = 0
        self.attempts = 3
        self.check = set()
        self.increase = 0

    def instruction(self):
        txt = 'Welcome to MoneyGen Nigeria Limited'
        new_str = txt.center(150)
        print(colored(new_str, 'magenta'))
        print('______________________________________________________________________________________________________________________________________________')
        print(colored('\nGAME INSTRUCTIONS:', 'cyan'))
        print("1. Answer each question with either 'true' or 'false'.\n2. You have a maximum of 3 attempts.\n3. The game comprises 10 questions, each worth 1 mark.\n4. Attempt count starts after missing a question or inputting an invalid answer.")

    def questions(self):
        while True:
            question_no = random.choice(list(the_questions.keys()))

            if question_no not in self.check:
                self.check.add(question_no)
                print(f'\n|{the_questions[question_no]}')

                question_ans = correct_answer[question_no]
                answer = input('Enter your answer: ').lower()

                if answer == question_ans:
                    self.score += 1
                    print(colored('Correct!', 'blue'))
                    if self.question_counter > 10:
                        self.question_counter += 1
                    break


                elif answer not in options:
                    self.attempts -= 1
                    print(colored("Invalid input. Please enter 'true' or 'false'.", "red"))
                    break

                else:
                    answer != question_ans
                    self.attempts -= 1
                    print(colored('Incorrect answer','red'))
                    break

    def price(self):
        amount = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        for value in amount:
            if self.score == value:
                self.increase = self.score * 10
        if self.increase > 1:
            print(colored(f'\nCongratulations {self.name}!, You just won ${self.increase}.', 'green'))
        else:
            self.increase < 1
            print(colored(f'\nSorry {self.name}, you did not win any money.', 'green'))
        if self.increase == 100:
            print(colored('You reached the Milestone!', 'green'))

In [ ]:
player1 = Player('Ayo Brown', 'Male', 21, 'Ogun state')
player1.instruction()
print(f"\n{colored('PLAYER INFO', 'cyan')}\nName:{colored(player1.name,'yellow')}\nGender:{colored(player1.gender,'yellow')}\nAge:{colored(player1.age, 'yellow')}\nState of origin:{colored(player1.state_of_origin,'yellow')}")
print('______________________________________________________________________________________________________________________________________________')
print(colored('>START<', 'cyan'))
for values in range(1,11):
    player1.questions()
    if player1.attempts == 0:
        print(colored('\nGame over!','red'))
        break
player1.price()

                                                         Welcome to MoneyGen Nigeria Limited
______________________________________________________________________________________________________________________________________________

GAME INSTRUCTIONS:
1. Answer each question with either 'true' or 'false'.
2. You have a maximum of 3 attempts.
3. The game comprises 10 questions, each worth 1 mark.
4. Attempt count starts after missing a question or inputting an invalid answer.

PLAYER INFO
Name:Ayo Brown
Gender:Male
Age:21
State of origin:Ogun state
______________________________________________________________________________________________________________________________________________
>START<

|The INSERT INTO statement is used in SQL to add new records (rows) to a table
Enter your answer: h
Invalid input. Please enter 'true' or 'false'.

|SQL's AVG() function is used to find the average value of a numeric row.
Enter your answer:
Invalid input. Please enter 'true' or 'false'.

|SQL's COUNT() function returns the number of rows that satisfy a specified condition.
Enter your answer:
Invalid input. Please enter 'true' or 'false'.

Game over!

Sorry Ayo Brown, you did not win any money.