In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/content/car_prices.csv')
data

,car_id,price,fuel type,gear type,Make,Model,Year of manufacture,Colour,Condition,Mileage,Engine Size,Selling Condition,Bought Condition,car,Trim,Drivetrain,Seats,Number of Cylinders,Horse Power,Registered city
0,icwAaDOmX573WiRRnLFPT237,2812500,Petrol,Automatic,Toyota,Corolla,2004,Silver,Nigerian Used,251732.0,1800.0,Registered,Registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ByZ3NlPy2x0arAIyrKazClUS,5000000,Petrol,Automatic,Acura,MDX,2007,Green,Foreign Used,224589.0,3700.0,Imported,Imported,SUV,NaN,NaN,NaN,NaN,NaN,NaN
2,2zG6Mh3kwyoTvWoeKHkV1oFH,7592000,Petrol,Automatic,Acura,TL,2012,White,Foreign Used,111334.0,3500.0,Imported,Imported,Sedan,SH-AWD Automatic Tech Package,All Wheel,5.0,6.0,309.0,NaN
3,7APLHOPlI93qsYK0ST4D4wB2,9880000,Petrol,Automatic,Land Rover,Range Rover,2012,Gray,Nigerian Used,72682.0,4000.0,Registered,Imported,SUV,NaN,NaN,NaN,NaN,NaN,NaN
4,zIrIDPJLd46eRQf9JFacc0e,4160000,Petrol,Automatic,Ford,Edge,2013,Gray,Nigerian Used,92118.0,3500.0,Registered,Registered,SUV,NaN,NaN,NaN,NaN,NaN,Lagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3717,C4Ly76wwazrtbYRAWkTnv2Q5,1924000,Petrol,Automatic,Toyota,RAV4,2003,Red,Nigerian Used,282769.0,2000.0,Registered,Imported,SUV,Automatic,All Wheel,5.0,4.0,NaN,Plateau
3718,jPA7XlJJxdwpZStlurumw59q,1890000,Petrol,Automatic,Mercedes-Benz,M Class,2002,Silver,Nigerian Used,182544.0,3200.0,Registered,Registered,SUV,ML 320,All Wheel,5.0,6.0,215.0,NaN
3719,g5szhuHeXu2djH1Z2be22G7E,1155000,Petrol,Automatic,Toyota,Camry,2000,Black,Nigerian Used,234354.0,2200.0,Registered,Registered,Sedan,LE 4dr Sedan (2.2L 4cyl 4A),Front,5.0,4.0,136.0,RIVERS
3720,mdZMNQK7Zez0cSS67Q9Quhzr,1260000,Petrol,Automatic,Toyota,RAV4,2001,Black,Nigerian Used,345926.0,2000.0,Registered,Registered,SUV,NaN,NaN,NaN,NaN,NaN,NaN
3721,fSUvulLwnXYlc1muFsrjrsAR,1872000,Petrol,Automatic,Honda,Civic,2007,Black,Nigerian Used,90330.0,1800.0,Registered,Registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3722 entries, 0 to 3721
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   car_id               3722 non-null   object
 1   price                3722 non-null   int64
 2   fuel type            3721 non-null   object
 3   gear type            3720 non-null   object
 4   Make                 3722 non-null   object
 5   Model                3722 non-null   object
 6   Year of manufacture  3722 non-null   int64
 7   Colour               3717 non-null   object
 8   Condition            3722 non-null   object
 9   Mileage              3663 non-null   float64
 10  Engine Size          3661 non-null   float64
 11  Selling Condition    3722 non-null   object
 12  Bought Condition     3722 non-null   object
 13  car                  1767 non-null   object
 14  Trim                 879 non-null    object
 15  Drivetrain           838 non-null    object
 16  Seats                788 non-null    float64
 17  Number of Cylinders  826 non-null    float64
 18  Horse Power          755 non-null    float64
 19  Registered city      1901 non-null   object
dtypes: float64(5), int64(2), object(13)
memory usage: 581.7+ KB

In [4]:
data.describe()

,price,Year of manufacture,Mileage,Engine Size,Seats,Number of Cylinders,Horse Power
count,3.722000e+03,3722.000000,3.663000e+03,3.661000e+03,788.000000,826.000000,755.000000
mean,4.514644e+06,2008.145889,1.949841e+05,1.108062e+04,5.285533,5.157385,208.831788
std,4.297012e+06,4.205670,1.395755e+05,1.091127e+05,0.800853,1.202795,70.940925
min,5.500000e+05,1979.000000,1.000000e+00,1.800000e+02,2.000000,4.000000,83.000000
25%,2.310000e+06,2005.000000,1.173945e+05,2.000000e+03,5.000000,4.000000,158.000000
50%,3.360000e+06,2008.000000,1.762900e+05,2.500000e+03,5.000000,6.000000,203.000000
75%,5.036250e+06,2011.000000,2.453815e+05,3.500000e+03,5.000000,6.000000,268.000000
max,6.240000e+07,2022.000000,2.456318e+06,3.500000e+06,8.000000,8.000000,585.000000

In [5]:
data.isnull().sum()

car_id                    0
price                     0
fuel type                 1
gear type                 2
Make                      0
Model                     0
Year of manufacture       0
Colour                    5
Condition                 0
Mileage                  59
Engine Size              61
Selling Condition         0
Bought Condition          0
car                    1955
Trim                   2843
Drivetrain             2884
Seats                  2934
Number of Cylinders    2896
Horse Power            2967
Registered city        1821
dtype: int64

In [6]:
data = data.drop_duplicates()

In [7]:
data.duplicated().sum()

0

In [8]:
data.shape

(3120, 20)

In [9]:
data.isnull().sum()

car_id                    0
price                     0
fuel type                 1
gear type                 2
Make                      0
Model                     0
Year of manufacture       0
Colour                    5
Condition                 0
Mileage                  51
Engine Size              50
Selling Condition         0
Bought Condition          0
car                    1643
Trim                   2378
Drivetrain             2418
Seats                  2458
Number of Cylinders    2425
Horse Power            2485
Registered city        1531
dtype: int64

In [10]:
#The thresh is 70%
data.isnull().sum() / 3120 * 100

car_id                  0.000000
price                   0.000000
fuel type               0.032051
gear type               0.064103
Make                    0.000000
Model                   0.000000
Year of manufacture     0.000000
Colour                  0.160256
Condition               0.000000
Mileage                 1.634615
Engine Size             1.602564
Selling Condition       0.000000
Bought Condition        0.000000
car                    52.660256
Trim                   76.217949
Drivetrain             77.500000
Seats                  78.782051
Number of Cylinders    77.724359
Horse Power            79.647436
Registered city        49.070513
dtype: float64

In [11]:
#1-What is the shape of the data
data.shape

(3120, 20)

In [17]:
#2-What columns are numeric
data.select_dtypes('number').columns.to_list()

['price',
 'Year of manufacture',
 'Mileage',
 'Engine Size',
 'Seats',
 'Number of Cylinders',
 'Horse Power']

In [16]:
#3-What columns are non-numeric
data.select_dtypes('object').columns.to_list()

['car_id',
 'fuel type',
 'gear type',
 'Make',
 'Model',
 'Colour',
 'Condition',
 'Selling Condition',
 'Bought Condition',
 'car',
 'Trim',
 'Drivetrain',
 'Registered city']

In [18]:
#4-How many null values do we have in each column
data.isnull().sum()

car_id                    0
price                     0
fuel type                 1
gear type                 2
Make                      0
Model                     0
Year of manufacture       0
Colour                    5
Condition                 0
Mileage                  51
Engine Size              50
Selling Condition         0
Bought Condition          0
car                    1643
Trim                   2378
Drivetrain             2418
Seats                  2458
Number of Cylinders    2425
Horse Power            2485
Registered city        1531
dtype: int64

In [19]:
#5-What is the total number of null values in the data
data.isnull().sum().sum()

15447

In [20]:
#6-Do we have duplicates in the data and how much
data = data.drop_duplicates()
data.duplicated().sum()

0

In [21]:
#7-Is there any column that we probably need to drop,drop such columns.
#The thresh is 70%
data.isnull().sum() / 3120 * 100

car_id                  0.000000
price                   0.000000
fuel type               0.032051
gear type               0.064103
Make                    0.000000
Model                   0.000000
Year of manufacture     0.000000
Colour                  0.160256
Condition               0.000000
Mileage                 1.634615
Engine Size             1.602564
Selling Condition       0.000000
Bought Condition        0.000000
car                    52.660256
Trim                   76.217949
Drivetrain             77.500000
Seats                  78.782051
Number of Cylinders    77.724359
Horse Power            79.647436
Registered city        49.070513
dtype: float64

In [22]:
data['car'].value_counts()

car
SUV                     951
Sedan                   321
Truck                    35
Hatchback                35
Minivan                  30
Coupe                    27
Crossover                22
Bus                      12
Van                      11
Station Wagon             8
Pickup                    7
Saloon                    7
Convertible               5
Pick-up Double Cabin      3
MUV                       3
Name: count, dtype: int64

In [23]:
#checking for the number of seat in a particular car type
data.query("car=='Truck'").isnull().sum()

car_id                  0
price                   0
fuel type               0
gear type               0
Make                    0
Model                   0
Year of manufacture     0
Colour                  0
Condition               0
Mileage                 1
Engine Size             1
Selling Condition       0
Bought Condition        0
car                     0
Trim                   24
Drivetrain             25
Seats                  26
Number of Cylinders    24
Horse Power            24
Registered city        14
dtype: int64

In [25]:
data.query("car=='Truck'")

,car_id,price,fuel type,gear type,Make,Model,Year of manufacture,Colour,Condition,Mileage,Engine Size,Selling Condition,Bought Condition,car,Trim,Drivetrain,Seats,Number of Cylinders,Horse Power,Registered city
29,wQajIZxTeX1HPesmV2Se9wxb,7360000,Petrol,Automatic,Toyota,Tacoma,2010,Gray,Nigerian Used,105530.0,3500.0,Registered,Imported,Truck,Access Cab Automatic,Rear Wheel,4.0,4.0,161.0,LAGOS
72,5czUputP1RHEgLGuCjntdtBQ,8984000,Petrol,Manual,Toyota,Hilux,2014,White,Nigerian Used,82115.0,2700.0,Registered,Registered,Truck,NaN,NaN,NaN,NaN,NaN,Lagos
92,5B55rWY4OQkKslv4EIitkcMH,27040000,Petrol,Automatic,Toyota,Tundra,2018,Silver,Foreign Used,72709.0,57000.0,Imported,Imported,Truck,NaN,NaN,NaN,NaN,NaN,NaN
239,oCwRkPwBxHHv3jeG1nLFqu5p,10400000,Petrol,Automatic,Toyota,Tundra,2008,Gray,Nigerian Used,51535.0,5700.0,Registered,Imported,Truck,NaN,NaN,NaN,NaN,NaN,ASABA
301,oNwznEsMENocBOAghHWluMqw,4725000,Petrol,Automatic,Toyota,Tacoma,2006,Silver,Nigerian Used,136226.0,4000.0,Registered,Imported,Truck,NaN,NaN,NaN,NaN,NaN,Lagos
347,wI2h5RpnGdw13z0I1vy70R8n,11550000,Petrol,Automatic,Toyota,Tundra,2012,Black,Nigerian Used,224520.0,5700.0,Registered,Imported,Truck,NaN,NaN,NaN,NaN,NaN,ABUJA
353,u1Z8cAEENdAntCswEdS3XhNC,3150000,Petrol,Automatic,Toyota,Tacoma,2002,Silver,Nigerian Used,314389.0,3400.0,Registered,Imported,Truck,NaN,NaN,NaN,NaN,NaN,Lagos
385,s4ET91pyDnON3NPCSxqt7ocQ,3150000,Petrol,Automatic,Toyota,Tacoma,2005,Gold,Nigerian Used,250649.0,4700.0,Registered,Imported,Truck,Access Cab I4 AWD,All Wheel,4.0,4.0,166.0,LAGOS
462,dsPUlTTYOb6CvQ9y3GMJOStQ,6300000,Petrol,Automatic,Ford,F-150,2012,Gray,Nigerian Used,416548.0,3500.0,Registered,Imported,Truck,FX4,All Wheel,NaN,8.0,365.0,Lagos
509,dvZOHzObIVDPwAJB9KDCuDpn,3150000,Petrol,Automatic,Honda,Ridgeline,2007,Blue,Nigerian Used,260475.0,3500.0,Registered,Registered,Truck,NaN,NaN,NaN,NaN,NaN,LAGOS
534,ayy7s5KyLNHTHl8kCNye8m1O,6448000,Petrol,Automatic,Honda,Ridgeline,2006,Gray,Foreign Used,298936.0,3500.0,Imported,Imported,Truck,RT,All Wheel,5.0,6.0,250.0,NaN
688,htPAdmZZ42MQNBgnBjjD75eE,3150000,Petrol,Manual,Nissan,Navara,2008,Gray,Nigerian Used,67608.0,NaN,Registered,Registered,Truck,NaN,NaN,NaN,NaN,NaN,Lagos
1615,vXWCcTFcc8P9s0D33UZhTThy,5250000,Petrol,Automatic,Toyota,Tacoma,2007,Blue,Nigerian Used,50290.0,2700.0,Registered,Imported,Truck,NaN,NaN,NaN,NaN,NaN,LAGOS
1777,iux78BLw6yb4hzXsc4X9fM9c,36170000,Petrol,Automatic,Ford,F-150,2015,Black,Foreign Used,197747.0,5000.0,Imported,Imported,Truck,NaN,NaN,NaN,NaN,NaN,NaN
1855,5KOVpatSk72Fde0X7jtJ9xWt,10500000,Petrol,Automatic,Ford,F-150,2012,Black,Nigerian Used,193434.0,3500.0,Registered,Imported,Truck,NaN,NaN,NaN,NaN,NaN,NaN
1914,14ZwoiTtGzSIvRhQ3FAphMFN,3740000,Petrol,Manual,Toyota,Tacoma,2006,White,Nigerian Used,4140.0,2700.0,Registered,Registered,Truck,NaN,NaN,NaN,NaN,NaN,OYO
1918,GgBtdGQ3QdI0N0Q2pwy4fef,5775000,Petrol,Manual,Mitsubishi,L200,2016,White,Nigerian Used,185151.0,2400.0,Registered,Registered,Truck,NaN,NaN,NaN,NaN,NaN,Lagos
1919,xkGgwZ5LRt67UOlB130w82KM,11440000,Petrol,Manual,Toyota,Hilux,2011,White,Nigerian Used,239251.0,2700.0,Registered,Registered,Truck,NaN,NaN,NaN,NaN,NaN,NaN
2004,hdEfvLPxlQCLK4XgYrv2Vb2G,6760000,Petrol,Manual,Toyota,Hilux,2009,White,Nigerian Used,98041.0,2700.0,Registered,Registered,Truck,2.7 VVT-i 4X4 SRX,All Wheel,2.0,4.0,160.0,LAGOS
2214,sn5ttumXhBYAvbsGLctMheOv,11440000,Petrol,Automatic,Toyota,Tundra,2010,Black,Nigerian Used,229282.0,5700.0,Registered,Imported,Truck,CrewMax Limited 5.7L,Rear Wheel,5.0,8.0,386.0,NaN
2232,nvxuhZbAFAmafAf6fb9FaLrL,4680000,Petrol,Automatic,Toyota,Tundra,2006,Gray,Nigerian Used,250464.0,4700.0,Registered,Imported,Truck,NaN,NaN,NaN,NaN,NaN,NaN
2421,oWUvsl6yF1WB62h8NacX39ho,3990000,Petrol,Automatic,Ford,F-150,2004,White,Nigerian Used,207843.0,5400.0,Registered,Registered,Truck,NaN,NaN,NaN,NaN,NaN,NaN
2529,xDfJ1xOgKjaDJReW8CR88ny0,5200000,Petrol,Automatic,Toyota,Tundra,2004,Gray,Nigerian Used,273601.0,4700.0,Registered,Imported,Truck,NaN,NaN,NaN,NaN,NaN,NaN
2564,v2PwZDoz3xtHmgKmXdmkdgQJ,4830000,Diesel,Automatic,Ford,E-350,2008,White,Foreign Used,781587.0,6000.0,Imported,Imported,Truck,NaN,NaN,NaN,NaN,NaN,NaN
2577,oNolGgfq3Op5Yxp97MSFkpqz,5512000,Petrol,Manual,Mitsubishi,L200,2014,White,Nigerian Used,313363.0,2300.0,Registered,Registered,Truck,Double Cab 2.5 180hp 4WD,All Wheel,5.0,4.0,180.0,Lagos
2818,BwwFLWIECEwKHTe6hi7Uqhr8,3600000,Petrol,Automatic,Ford,Ranger,2008,Black,Foreign Used,308951.0,3000.0,Imported,Imported,Truck,NaN,NaN,NaN,NaN,NaN,NaN
2958,rOBaYsofvs2qUYtdnVOqW7JN,4515000,Petrol,Manual,Ford,Ranger,2011,White,Nigerian Used,176732.0,2400.0,Registered,Brand new,Truck,XLT,Rear Wheel,NaN,4.0,145.0,Akwa-Ibom
2961,BaRGy8oI4DjRsqfIzaBlw0b6,7875000,Petrol,Automatic,Nissan,Titan,2010,Gray,Nigerian Used,211155.0,5600.0,Registered,Imported,Truck,Crew Cab SE 4x4,All Wheel,6.0,8.0,321.0,LAGOS
3035,iebtDvGHEYkcVJASNzzSa6Ws,5750000,Petrol,Manual,Toyota,Hilux,2009,White,Nigerian Used,139426.0,2700.0,Registered,Registered,Truck,NaN,NaN,NaN,NaN,NaN,KWARA
3085,B87APvJi9mTaiErQhxjfmYaM,12600000,Petrol,Automatic,Toyota,Tacoma,2013,Black,Foreign Used,70413.0,3500.0,Imported,Imported,Truck,Acces Cab 4x2 2.7L 4-Cyl. 4-Speed Automatic,Rear Wheel,4.0,4.0,159.0,NaN
3151,dwcwhnpUX9RW1i9k6TcWZOQu,4725000,Petrol,Manual,Toyota,Hilux,2005,White,Nigerian Used,NaN,27000.0,Registered,Registered,Truck,NaN,NaN,NaN,NaN,NaN,Abuja
3153,BEw03kE0DMHsfAnMYIGOt3oz,1680000,Petrol,Automatic,Nissan,Titan,2004,Black,Nigerian Used,162548.0,5600.0,Registered,Registered,Truck,NaN,NaN,NaN,NaN,NaN,NaN
3185,9YRVvzXqJD0t0oJ40DI0aRTN,3725000,Petrol,Manual,Nissan,Frontier,2015,Blue,Nigerian Used,61244.0,4000.0,Registered,Registered,Truck,NaN,NaN,NaN,NaN,NaN,ABUJA
3214,aFPoIy5KPQplwFjbMd6M6jdm,2100000,Petrol,Automatic,Nissan,Titan,2005,Gray,Nigerian Used,232111.0,5600.0,Registered,Registered,Truck,Crew Cab,NaN,5.0,8.0,309.0,ABUJA
3583,6hh8lseFGRpSyDBEC58iQHdQ,3885000,Petrol,Manual,Mitsubishi,L200,2006,White,Nigerian Used,632583.0,3000.0,Registered,Imported,Truck,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
seat_mapping = {'SUV': 7}
data['Seats'] = data['Seats'].fillna(data['car'].map(seat_mapping))

In [27]:
data

,car_id,price,fuel type,gear type,Make,Model,Year of manufacture,Colour,Condition,Mileage,Engine Size,Selling Condition,Bought Condition,car,Trim,Drivetrain,Seats,Number of Cylinders,Horse Power,Registered city
0,icwAaDOmX573WiRRnLFPT237,2812500,Petrol,Automatic,Toyota,Corolla,2004,Silver,Nigerian Used,251732.0,1800.0,Registered,Registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ByZ3NlPy2x0arAIyrKazClUS,5000000,Petrol,Automatic,Acura,MDX,2007,Green,Foreign Used,224589.0,3700.0,Imported,Imported,SUV,NaN,NaN,7.0,NaN,NaN,NaN
2,2zG6Mh3kwyoTvWoeKHkV1oFH,7592000,Petrol,Automatic,Acura,TL,2012,White,Foreign Used,111334.0,3500.0,Imported,Imported,Sedan,SH-AWD Automatic Tech Package,All Wheel,5.0,6.0,309.0,NaN
3,7APLHOPlI93qsYK0ST4D4wB2,9880000,Petrol,Automatic,Land Rover,Range Rover,2012,Gray,Nigerian Used,72682.0,4000.0,Registered,Imported,SUV,NaN,NaN,7.0,NaN,NaN,NaN
4,zIrIDPJLd46eRQf9JFacc0e,4160000,Petrol,Automatic,Ford,Edge,2013,Gray,Nigerian Used,92118.0,3500.0,Registered,Registered,SUV,NaN,NaN,7.0,NaN,NaN,Lagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3717,C4Ly76wwazrtbYRAWkTnv2Q5,1924000,Petrol,Automatic,Toyota,RAV4,2003,Red,Nigerian Used,282769.0,2000.0,Registered,Imported,SUV,Automatic,All Wheel,5.0,4.0,NaN,Plateau
3718,jPA7XlJJxdwpZStlurumw59q,1890000,Petrol,Automatic,Mercedes-Benz,M Class,2002,Silver,Nigerian Used,182544.0,3200.0,Registered,Registered,SUV,ML 320,All Wheel,5.0,6.0,215.0,NaN
3719,g5szhuHeXu2djH1Z2be22G7E,1155000,Petrol,Automatic,Toyota,Camry,2000,Black,Nigerian Used,234354.0,2200.0,Registered,Registered,Sedan,LE 4dr Sedan (2.2L 4cyl 4A),Front,5.0,4.0,136.0,RIVERS
3720,mdZMNQK7Zez0cSS67Q9Quhzr,1260000,Petrol,Automatic,Toyota,RAV4,2001,Black,Nigerian Used,345926.0,2000.0,Registered,Registered,SUV,NaN,NaN,7.0,NaN,NaN,NaN
3721,fSUvulLwnXYlc1muFsrjrsAR,1872000,Petrol,Automatic,Honda,Civic,2007,Black,Nigerian Used,90330.0,1800.0,Registered,Registered,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data['Drivetrain'].fillna(data['Drivetrain'].mode()[0], inplace = True)

In [ ]:
data['car'].fillna(data['car'].mode()[0], inplace = True)

In [ ]:
data['Seats'].fillna(data['Seats'].median(), inplace = True)

In [ ]:
data['Number of Cylinders'].fillna(data['Number of Cylinders'].median(), inplace = True)

In [ ]:
data['Horse Power'].fillna(data['Horse Power'].median(), inplace = True)

In [ ]:
data['Trim'].fillna(data['Trim'].mode()[0], inplace = True)

In [ ]:
data['Registered city'].fillna(data['Registered city'].mode()[0], inplace = True)